run_mode: "release"
logger:
  color: false

app:
  app_name: "maxblog-me-template"
  version: "0.1.0"

server:
  host: "0.0.0.0"
  port: 9200
  shutdown_timeout: 10
  tags:
    - maxblog-me-template
    - maxblog

upstream:
  maxblog_fe_template:
    protocol: "http"
    domain: "127.0.0.1:9100"
    host: "127.0.0.1"
    port: 9100
    secure: true

downstream:
  maxblog_be_template:
    host: "127.0.0.1"
    port: 9300

redis:
  host: "0.0.0.0"
  port: 6379

consul:
  host: "0.0.0.0"
  port: 8500

